// client/da/grilling/examples-dj/biguml-example/packages/biguml-components/src/property-palette/property-palette.component.ts
/*********************************************************************************
 * Copyright (c) 2023 borkdominik and others.
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at https://opensource.org/licenses/MIT.
 *
 * SPDX-License-Identifier: MIT
 *********************************************************************************/

import {
  ElementBoolProperty,
  ElementChoiceProperty,
  ElementProperties,
  ElementProperty,
  ElementReferenceProperty,
  ElementTextProperty,
  RefreshPropertyPaletteAction,
  UpdateElementPropertyAction
} from '@borkdominik-biguml/biguml-protocol';
import { Action } from '@eclipse-glsp/protocol';
import { Checkbox as VSCodeCheckbox, Dropdown as VSCodeDropdown, TextField as VSCodeTextField } from '@vscode/webview-ui-toolkit';
import { html, nothing, PropertyValues, TemplateResult } from 'lit';
import { property, state } from 'lit/decorators.js';
import { keyed } from 'lit/directives/keyed.js';
import { when } from 'lit/directives/when.js';
import { groupBy } from 'lodash';
import { BigElement } from '../base/component';
import '../global';
import { PropertyPaletteStyle } from './property-palette.style';
import { PropertyDeleteEventDetail, PropertyNameChangeDetail, PropertyOrderDetail } from './reference/property-palette-reference.component';

export function definePropertyPalette(): void {
    customElements.define('big-property-palette', PropertyPalette);
}

export class PropertyPalette extends BigElement {
    static override styles = [...super.styles, PropertyPaletteStyle.style];

    @property()
    clientId?: string;

    @property({ type: Object })
    properties?: ElementProperties;

    @state()
    protected searchText?: string;

    @state()
    protected navigationIds: { [key: string]: { from: string; to: string }[] } = {};

    protected override render(): TemplateResult<1> {
        return html`${keyed(this.properties?.elementId, html`<div>${this.headerTemplate()} ${this.bodyTemplate()}</div>`)}`;
    }

    protected override updated(changedProperties: PropertyValues<this>): void {
        if (changedProperties.has('properties') && this.clientId !== undefined) {
            const ids = this.navigationIds[this.clientId];

            if (this.properties === undefined || ids?.at(-1)?.to !== this.properties.elementId) {
                this.navigationIds[this.clientId] = [];
            }
        }
    }

    protected headerTemplate(): TemplateResult<1> {
        return html`<header>
            ${when(
                this.clientId && this.navigationIds[this.clientId]?.length > 0,
                () => html`
                    <vscode-button id="navigate-back" appearance="icon" @click="${this.onNavigateBack}"
                        ><span class="codicon codicon-chevron-left"></span
                    ></vscode-button>
                `,
                () => nothing
            )}
            ${this.properties === undefined ? nothing : html`<h3 class="title">${this.properties?.label}</h3>`}
        </header>`;
    }

    protected bodyTemplate(): TemplateResult<1> {
        if (this.properties === undefined) {
            return html`<div class="no-data-message">The active diagram does not provide property information.</div>`;
        }

        const items = this.properties.items;
        const filteredItems = items.filter(item => {
            const label: string = (item as any)['label'];

            if (label !== undefined && this.searchText !== undefined) {
                return label.toLowerCase().includes(this.searchText.toLocaleLowerCase());
            }

            return true;
        });
        const { references: referenceItems, other: gridItems } = extractReferences(filteredItems);

        const gridTemplates = gridItems.map(item => {
            if (ElementTextProperty.is(item)) {
                return this.textFieldTemplate(item);
            } else if (ElementBoolProperty.is(item)) {
                return this.checkboxTemplate(item);
            } else if (ElementChoiceProperty.is(item)) {
                return this.dropdownTemplate(item);
            }

            return html`${nothing}`;
        });

        const referenceTemplates = referenceItems.map(item => {
            if (ElementReferenceProperty.is(item)) {
                return this.referenceTemplate(item);
            }

            return html`${nothing}`;
        });

        return html`<div class="body">
            <vscode-text-field
                id="search"
                placeholder="Search"
                .value="${this.searchText}"
                @input="${(event: any) => (this.searchText = event.target?.value)}"
            >
                <span slot="start" class="codicon codicon-search"></span>
            </vscode-text-field>
            <vscode-divider></vscode-divider>
            ${when(
                gridTemplates.length > 0,
                () => html`<div class="grid">${gridTemplates}</div>`,
                () => nothing
            )}
            ${when(
                gridTemplates.length > 0 && referenceTemplates.length > 0,
                () => html`<vscode-divider></vscode-divider>`,
                () => nothing
            )}
            ${referenceTemplates}
        </div>`;
    }

    protected textFieldTemplate(item: ElementTextProperty): TemplateResult<1> {
        const onChange = (event: CustomEvent): void => {
            const target = event.target as VSCodeTextField;
            this.onPropertyChange(item, target.value);
        };

        return html`<div class="grid-label">${item.label}</div>
            <div class="grid-value grid-flex">
                <vscode-text-field .value="${item.text}" @change="${onChange}" ?disabled="${item.disabled}"></vscode-text-field>
            </div>`;
    }

    protected checkboxTemplate(item: ElementBoolProperty): TemplateResult<1> {
        const onChange = (event: CustomEvent): void => {
            const target = event.target as VSCodeCheckbox;
            this.onPropertyChange(item, '' + target.checked);
        };

        return html`<div class="grid-label">${item.label}</div>
            <div class="grid-value">
                <vscode-checkbox
                    class="bool-item"
                    ?checked="${item.value}"
                    @change="${onChange}"
                    ?disabled="${item.disabled}"
                ></vscode-checkbox>
            </div>`;
    }

    protected dropdownTemplate(item: ElementChoiceProperty): TemplateResult<1> {
        const onChange = (event: CustomEvent): void => {
            const target = event.target as VSCodeDropdown;
            this.onPropertyChange(item, target.value);
        };

        return html`<div class="grid-label">${item.label}</div>
            <div class="grid-value grid-flex">
                <vscode-dropdown .value="${item.choice}" @change="${onChange}" ?disabled="${item.disabled}">
                    <div slot="selected-value">${item.choices.find(c => c.value === item.choice)?.label}</div>
                    ${item.choices.map(
                        choice =>
                            html`<vscode-option .value="${choice.value}">
                                <div class="dropdown-option">
                                    <span>${choice.label}</span>
                                    ${when(
                                        choice.secondaryText,
                                        () => html`<small>${choice.secondaryText}</small>`,
                                        () => nothing
                                    )}
                                </div>
                            </vscode-option>`
                    )}
                </vscode-dropdown>
            </div>`;
    }

    protected referenceTemplate(item: ElementReferenceProperty): TemplateResult<1> {
        return html`<big-property-palette-reference
            .item="${item}"
            @property-navigate="${this.onPropertyNavigate}"
            @property-order-change="${this.onOrderChange}"
            @property-name-change="${this.onPropertyNameChange}"
            @property-create="${this.onPropertyCreate}"
            @property-delete="${this.onPropertyDelete}"
        ></big-property-palette-reference>`;
    }

    protected onNavigateBack(): void {
        if (this.clientId) {
            const ids = this.navigationIds[this.clientId];
            if (ids.length > 0) {
                const elementId = ids.pop()?.from;
                this.dispatchEvent(
                    new CustomEvent<Action>('dispatch-action', {
                        detail: RefreshPropertyPaletteAction.create({
                            elementId
                        })
                    })
                );
            }
        }
    }

    protected onPropertyChange(item: ElementProperty, value: string): void {
        const { elementId, propertyId } = item;

        this.dispatchEvent(
            new CustomEvent<Action>('dispatch-action', {
                detail: UpdateElementPropertyAction.create({
                    elementId,
                    propertyId,
                    value
                })
            })
        );
    }

    protected onOrderChange(event: CustomEvent<PropertyOrderDetail>): void {
        const { element, updates } = event.detail;

        this.dispatchEvent(
            new CustomEvent<Action>('dispatch-action', {
                detail: UpdateElementPropertyAction.create({
                    elementId: element.elementId,
                    propertyId: `${element.propertyId}_INDEX`,
                    value: JSON.stringify(updates)
                })
            })
        );
    }

    protected onPropertyNavigate(event: CustomEvent<ElementReferenceProperty.Reference>): void {
        const { elementId } = event.detail;
        if (this.properties && this.clientId) {
            this.navigationIds[this.clientId] = [
                ...(this.navigationIds[this.clientId] ?? []),
                {
                    from: this.properties.elementId,
                    to: elementId
                }
            ];
        }

        this.dispatchEvent(
            new CustomEvent<Action>('dispatch-action', {
                detail: RefreshPropertyPaletteAction.create({
                    elementId
                })
            })
        );
    }

    protected onPropertyNameChange(event: CustomEvent<PropertyNameChangeDetail>): void {
        const { elementId, name } = event.detail;

        this.dispatchEvent(
            new CustomEvent<Action>('dispatch-action', {
                detail: UpdateElementPropertyAction.create({
                    elementId,
                    propertyId: 'NAME',
                    value: name
                })
            })
        );
    }

    protected onPropertyCreate(event: CustomEvent<ElementReferenceProperty.CreateReference>): void {
        this.dispatchEvent(
            new CustomEvent<Action>('dispatch-action', {
                detail: event.detail.action
            })
        );
    }

    protected onPropertyDelete(event: CustomEvent<PropertyDeleteEventDetail>): void {
        this.dispatchEvent(
            new CustomEvent<Action[]>('dispatch-action', {
                detail: event.detail.references.flatMap(r => r.deleteActions)
            })
        );
    }
}

function extractReferences(items: ElementProperty[]): { references: ElementReferenceProperty[]; other: ElementProperty[] } {
    const group = groupBy(items, item => item.type === 'REFERENCE');

    return {
        references: (group['true'] as ElementReferenceProperty[]) ?? [],
        other: group['false'] ?? []
    };
}

// client/packages/big-property-palette/src/env/browser/property-palette.component.tsx
/**********************************************************************************
 * Copyright (c) 2025 borkdominik and others.
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at https://opensource.org/licenses/MIT.
 *
 * SPDX-License-Identifier: MIT
 **********************************************************************************/

import { BigCheckbox, BigDropdown, BigTextField, VSCodeContext } from '@borkdominik-biguml/big-components';
import {
    ElementBoolProperty,
    ElementChoiceProperty,
    ElementReferenceProperty,
    ElementTextProperty,
    RequestPropertyPaletteAction,
    SetNavigationIdNotification,
    SetPropertyPaletteAction,
    UpdateElementPropertyAction,
    type ElementProperties,
    type ElementProperty
} from '@borkdominik-biguml/big-property-palette';
import { type Action } from '@eclipse-glsp/protocol';
import { VSCodeButton, VSCodeDivider, VSCodeTextField } from '@vscode/webview-ui-toolkit/react/index.js';
import { groupBy } from 'lodash';
import { useCallback, useContext, useEffect, useState, type ChangeEvent, type ReactElement } from 'react';
import { PropertyPaletteReferenceItem } from './property-palette-reference-item.component.js';

export function PropertyPalette(): ReactElement {
    const { clientId, dispatchNotification, listenAction, dispatchAction } = useContext(VSCodeContext);
    const [properties, setProperties] = useState<ElementProperties | undefined>();
    const [navigationIds, setNavigationIds] = useState<{ [key: string]: { from: string; to: string }[] }>({});
    const [searchText, setSearchText] = useState<string>('');

    const onAction = useCallback((action: Action) => {
        if (SetPropertyPaletteAction.is(action)) {
            if (action.palette === undefined) {
                setProperties(undefined);
            } else {
                const sortedProperties: ElementProperties = {
                    ...action.palette,
                    items: action.palette.items.sort((itemA, itemB) => {
                        if ('label' in itemA && 'label' in itemB) {
                            return (itemA.label as string).localeCompare(itemB.label as string);
                        }

                        return 0;
                    })
                };
                setProperties(sortedProperties);
            }
        }
    }, []);

    useEffect(() => {
        listenAction(onAction);
    });

    document.addEventListener('contextmenu', event => {
        event.stopImmediatePropagation();
    });

    useEffect(() => {
        if (clientId !== undefined) {
            setNavigationIds(navigationIds => {
                const ids = navigationIds[clientId];

                if (properties === undefined || ids?.at(-1)?.to !== properties.elementId) {
                    return {
                        ...navigationIds,
                        [clientId]: []
                    };
                }

                return navigationIds;
            });
        }
    }, [properties, clientId]);

    useEffect(() => {
        if (!clientId || !navigationIds[clientId] || navigationIds[clientId].length === 0) {
            return;
        }

        const ids = [...navigationIds[clientId]];
        dispatchNotification(SetNavigationIdNotification, ids.at(-1)!.to);
    }, [clientId, dispatchNotification, navigationIds]);

    const onNavigateBack = useCallback(() => {
        if (!clientId) {
            return;
        }

        const ids = [...navigationIds[clientId]];
        if (ids.length > 0) {
            const elementId = ids.pop()?.from;
            setNavigationIds({
                ...navigationIds,
                [clientId]: ids
            });
            dispatchAction(
                RequestPropertyPaletteAction.create({
                    elementId
                })
            );
            dispatchNotification(SetNavigationIdNotification, elementId);
        }
    }, [clientId, navigationIds, dispatchAction, dispatchNotification]);

    const onPropertyChange = useCallback(
        (item: ElementProperty, value: string) => {
            const { elementId, propertyId } = item;

            dispatchAction(
                UpdateElementPropertyAction.create({
                    elementId,
                    propertyId,
                    value
                })
            );
        },
        [dispatchAction]
    );

    const onPropertyNavigate = useCallback(
        (event: ElementReferenceProperty.Reference) => {
            const { elementId } = event;
            if (properties && clientId) {
                setNavigationIds({
                    ...navigationIds,
                    [clientId]: [
                        ...(navigationIds[clientId] ?? []),
                        {
                            from: properties.elementId,
                            to: elementId
                        }
                    ]
                });
            }

            dispatchAction(
                RequestPropertyPaletteAction.create({
                    elementId
                })
            );
        },
        [properties, clientId, dispatchAction, navigationIds]
    );

    const renderReference = useCallback(
        (item: ElementReferenceProperty) => {
            return (
                <PropertyPaletteReferenceItem
                    key={`${item.elementId}-${item.propertyId}`}
                    item={item}
                    onPropertyNavigate={onPropertyNavigate}
                />
            );
        },
        [onPropertyNavigate]
    );

    const renderHeader = useCallback(() => {
        if (clientId && navigationIds[clientId]?.length > 0) {
            return (
                <header>
                    <VSCodeButton appearance='icon' id='navigate-back' onClick={onNavigateBack}>
                        <span className='codicon codicon-chevron-left' />
                    </VSCodeButton>
                    <h3 className='title'>{properties?.label}</h3>
                </header>
            );
        }

        return <header>{properties === undefined ? '' : <h3 className='title'>{properties?.label}</h3>}</header>;
    }, [clientId, navigationIds, onNavigateBack, properties]);

    const renderBody = useCallback(() => {
        if (!properties) {
            return <div className='no-data-message'>The active diagram does not provide property information.</div>;
        }

        const items = properties.items;
        const filteredItems = items.filter((item: any) => {
            const label: string = item.label;

            if (label !== undefined && searchText.trim().length > 0) {
                return label.toLowerCase().includes(searchText.toLowerCase());
            }

            return true;
        });

        const { references: referenceItems, other: gridItems } = extractReferences(filteredItems);

        const gridTemplates = gridItems.map((item: any) => {
            if (ElementTextProperty.is(item)) {
                return (
                    <BigTextField
                        key={`${item.elementId}-${item.propertyId}`}
                        label={item.label}
                        value={item.text}
                        onDidChangeValue={value => onPropertyChange(item, value)}
                    />
                );
            } else if (ElementBoolProperty.is(item)) {
                return (
                    <BigCheckbox
                        key={`${item.elementId}-${item.propertyId}`}
                        label={item.label}
                        value={item.value}
                        onDidChangeValue={value => onPropertyChange(item, value + '')}
                    />
                );
            } else if (ElementChoiceProperty.is(item)) {
                return (
                    <BigDropdown
                        key={`${item.elementId}-${item.propertyId}`}
                        label={item.label}
                        disabled={item.disabled}
                        choice={item.choice}
                        choices={item.choices}
                        onDidChangeValue={value => onPropertyChange(item, value)}
                    ></BigDropdown>
                );
            }

            return null;
        });

        const referenceTemplates = referenceItems.map(item => {
            if (ElementReferenceProperty.is(item)) {
                return renderReference(item);
            }

            return null;
        });

        return (
            <div className='body'>
                <VSCodeTextField
                    id='search'
                    onInput={((event: ChangeEvent<HTMLInputElement>) => setSearchText(event.target.value)) as any}
                    placeholder='Search'
                    value={searchText}
                >
                    <span className='codicon codicon-search' slot='start' />
                </VSCodeTextField>

                <VSCodeDivider />

                {gridTemplates.length > 0 && <div className='grid'>{gridTemplates}</div>}

                {gridTemplates.length > 0 && referenceTemplates.length > 0 && <VSCodeDivider />}

                {referenceTemplates}
            </div>
        );
    }, [onPropertyChange, properties, renderReference, searchText]);

    return (
        <div>
            {renderHeader()}
            {renderBody()}
        </div>
    );
}

function extractReferences(items: ElementProperty[]): { references: ElementReferenceProperty[]; other: ElementProperty[] } {
    const group = groupBy(items, item => item.type === 'REFERENCE');

    return {
        references: (group['true'] as ElementReferenceProperty[]) ?? [],
        other: group['false'] ?? []
    };
}
