// client/packages/big-property-palette/src/browser/property-palette.component.tsx
/**********************************************************************************
 * Copyright (c) 2025 borkdominik and others.
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at https://opensource.org/licenses/MIT.
 *
 * SPDX-License-Identifier: MIT
 **********************************************************************************/

import { BigCheckbox, BigDropdown, BigTextField, VSCodeContext } from '@borkdominik-biguml/big-components';
import { type Action } from '@eclipse-glsp/protocol';
import { VSCodeButton, VSCodeDivider, VSCodeTextField } from '@vscode/webview-ui-toolkit/react';
import { groupBy } from 'lodash';
import { useCallback, useContext, useEffect, useState, type ChangeEvent, type ReactElement } from 'react';
import {
    ElementBoolProperty,
    ElementChoiceProperty,
    ElementReferenceProperty,
    ElementTextProperty,
    RefreshPropertyPaletteAction,
    SetPropertyPaletteAction,
    UpdateElementPropertyAction,
    type ElementProperties,
    type ElementProperty
} from '../common/index.js';
import {
    PropertyPaletteReferenceItem,
    type PropertyDeleteEventDetail,
    type PropertyNameChangeDetail,
    type PropertyOrderDetail
} from './property-palette-reference-item.component.js';

export function PropertyPalette(): ReactElement {
    const { clientId, listenAction, dispatchAction } = useContext(VSCodeContext);
    const [properties, setProperties] = useState<ElementProperties | undefined>();
    const [navigationIds, setNavigationIds] = useState<{ [key: string]: { from: string; to: string }[] }>({});
    const [searchText, setSearchText] = useState<string>('');

    const onNotification = useCallback((action: Action) => {
        if (SetPropertyPaletteAction.is(action)) {
            setProperties(action.palette);
        }
    }, []);

    useEffect(() => {
        listenAction(onNotification);
    });

    document.addEventListener('contextmenu', event => {
        event.stopImmediatePropagation();
    });

    useEffect(() => {
        if (clientId !== undefined) {
            setNavigationIds(navigationIds => {
                const ids = navigationIds[clientId];

                if (properties === undefined || ids?.at(-1)?.to !== properties.elementId) {
                    return {
                        ...navigationIds,
                        [clientId]: []
                    };
                }

                return navigationIds;
            });
        }
    }, [properties, clientId]);

    const onNavigateBack = useCallback(() => {
        if (!clientId) {
            return;
        }

        const ids = [...navigationIds[clientId]];
        if (ids.length > 0) {
            const elementId = ids.pop()?.from;
            dispatchAction(
                RefreshPropertyPaletteAction.create({
                    elementId
                })
            );
        }
    }, [clientId, navigationIds, dispatchAction]);

    const onPropertyChange = useCallback(
        (item: ElementProperty, value: string) => {
            const { elementId, propertyId } = item;

            dispatchAction(
                UpdateElementPropertyAction.create({
                    elementId,
                    propertyId,
                    value
                })
            );
        },
        [dispatchAction]
    );

    const onOrderChange = useCallback(
        (event: PropertyOrderDetail) => {
            const { element, updates } = event;

            dispatchAction(
                UpdateElementPropertyAction.create({
                    elementId: element.elementId,
                    propertyId: `${element.propertyId}_index`,
                    value: JSON.stringify(updates)
                })
            );
        },
        [dispatchAction]
    );

    const onPropertyNavigate = useCallback(
        (event: ElementReferenceProperty.Reference) => {
            const { elementId } = event;
            if (properties && clientId) {
                setNavigationIds({
                    ...navigationIds,
                    [clientId]: [
                        ...(navigationIds[clientId] ?? []),
                        {
                            from: properties.elementId,
                            to: elementId
                        }
                    ]
                });
            }

            dispatchAction(
                RefreshPropertyPaletteAction.create({
                    elementId
                })
            );
        },
        [properties, clientId, dispatchAction, navigationIds]
    );

    const onPropertyNameChange = useCallback(
        (event: PropertyNameChangeDetail) => {
            const { elementId, name } = event;

            dispatchAction(
                UpdateElementPropertyAction.create({
                    elementId,
                    propertyId: 'name',
                    value: name
                })
            );
        },
        [dispatchAction]
    );

    const onPropertyCreate = useCallback(
        (event: ElementReferenceProperty.CreateReference) => {
            dispatchAction(event.action);
        },
        [dispatchAction]
    );

    const onPropertyDelete = useCallback(
        (event: PropertyDeleteEventDetail) => {
            dispatchAction(event.references.flatMap(r => r.deleteActions) as any as Action);
        },
        [dispatchAction]
    );

    const renderReference = useCallback(
        (item: ElementReferenceProperty) => {
            return (
                <PropertyPaletteReferenceItem
                    item={item}
                    onPropertyCreate={onPropertyCreate}
                    onPropertyDelete={onPropertyDelete}
                    onPropertyNameChange={onPropertyNameChange}
                    onPropertyNavigate={onPropertyNavigate}
                    onPropertyOrderChange={onOrderChange}
                />
            );
        },
        [onOrderChange, onPropertyCreate, onPropertyDelete, onPropertyNameChange, onPropertyNavigate]
    );

    const renderHeader = useCallback(() => {
        if (clientId && navigationIds[clientId]?.length > 0) {
            return (
                <header>
                    <VSCodeButton appearance='icon' id='navigate-back' onClick={onNavigateBack}>
                        <span className='codicon codicon-chevron-left' />
                    </VSCodeButton>
                </header>
            );
        }

        return <header>{properties === undefined ? '' : <h3 className='title'>{properties?.label}</h3>}</header>;
    }, [clientId, navigationIds, onNavigateBack, properties]);

    const renderBody = useCallback(() => {
        if (!properties) {
            return <div className='no-data-message'>The active diagram does not provide property information.</div>;
        }

        const items = properties.items;
        const filteredItems = items.filter((item: any) => {
            const label: string = item.label;

            if (label !== undefined && searchText.trim().length > 0) {
                return label.toLowerCase().includes(searchText.toLowerCase());
            }

            return true;
        });

        const { references: referenceItems, other: gridItems } = extractReferences(filteredItems);

        const gridTemplates = gridItems.map((item: any) => {
            if (ElementTextProperty.is(item)) {
                return (
                    <BigTextField
                        key={item.propertyId}
                        label={item.label}
                        value={item.text}
                        onDidChangeValue={value => onPropertyChange(item, value)}
                    />
                );
            } else if (ElementBoolProperty.is(item)) {
                return (
                    <BigCheckbox
                        key={item.propertyId}
                        label={item.label}
                        value={item.value}
                        onDidChangeValue={value => onPropertyChange(item, value + '')}
                    />
                );
            } else if (ElementChoiceProperty.is(item)) {
                return (
                    <BigDropdown
                        key={item.propertyId}
                        label={item.label}
                        disabled={item.disabled}
                        choice={item.choice}
                        choices={item.choices}
                        onDidChangeValue={value => onPropertyChange(item, value)}
                    ></BigDropdown>
                );
            }

            return null;
        });

        const referenceTemplates = referenceItems.map((item: any) => {
            if (ElementReferenceProperty.is(item)) {
                return renderReference(item);
            }

            return null;
        });

        return (
            <div className='body'>
                <VSCodeTextField
                    id='search'
                    onInput={((event: ChangeEvent<HTMLInputElement>) => setSearchText(event.target.value)) as any}
                    placeholder='Search'
                    value={searchText}
                >
                    <span className='codicon codicon-search' slot='start' />
                </VSCodeTextField>

                <VSCodeDivider />

                {gridTemplates.length > 0 && <div className='grid'>{gridTemplates}</div>}

                {gridTemplates.length > 0 && referenceTemplates.length > 0 && <VSCodeDivider />}

                {referenceTemplates}
            </div>
        );
    }, [onPropertyChange, properties, renderReference, searchText]);

    return (
        <div>
            {renderHeader()}
            {renderBody()}
        </div>
    );
}

function extractReferences(items: ElementProperty[]): { references: ElementReferenceProperty[]; other: ElementProperty[] } {
    const group = groupBy(items, item => item.type === 'REFERENCE');

    return {
        references: (group['true'] as ElementReferenceProperty[]) ?? [],
        other: group['false'] ?? []
    };
}

// client/packages/uml-vscode-integration/webview/src/property-palette/property-palette.component.ts
/*********************************************************************************
 * Copyright (c) 2023 borkdominik and others.
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at https://opensource.org/licenses/MIT.
 *
 * SPDX-License-Identifier: MIT
 *********************************************************************************/

import '../vscode/toolkit';
import './property-palette-reference.component';

import {
    ElementBoolProperty,
    ElementChoiceProperty,
    ElementProperties,
    ElementProperty,
    ElementReferenceProperty,
    ElementTextProperty,
    RefreshPropertyPaletteAction,
    UpdateElementPropertyAction
} from '@borkdominik-biguml/uml-common';
import { Action, DeleteElementOperation } from '@eclipse-glsp/protocol';
import { Checkbox as VSCodeCheckbox, Dropdown as VSCodeDropdown, TextField as VSCodeTextField } from '@vscode/webview-ui-toolkit';
import { css, html, nothing, TemplateResult } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import { keyed } from 'lit/directives/keyed.js';
import { when } from 'lit/directives/when.js';
import { groupBy } from 'lodash';
import { BigUMLComponent } from '../webcomponents/component';
import { PropertyDeleteEventDetail, PropertyNameChangeDetail, PropertyOrderDetail } from './property-palette-reference.component';

@customElement('biguml-property-palette')
export class PropertyPalette extends BigUMLComponent {
    static override styles = [
        ...super.styles,
        css`
            .body {
                display: flex;
                flex-direction: column;
            }

            .search {
                margin-bottom: 6px;
            }

            .grid {
                display: grid;
                grid-template-columns: [label-start] 1fr [value-start] 1fr;
                gap: 6px 6px;
                justify-items: stretch;
                align-items: center;
                margin: 6px 0;
            }

            .grid-label {
                grid-column-start: label-start;
            }

            .grid-value {
                grid-column-start: value-start;
                overflow: hidden;
            }

            .grid-flex {
                display: flex;
                flex-direction: column;
            }

            .reference-item .create-reference {
                color: var(--uml-successBackground);
            }

            .reference-item .delete {
                color: var(--uml-errorForeground);
            }
        `
    ];

    @property({ type: Object })
    properties?: ElementProperties = undefined;

    @state()
    protected searchText?: string;

    override render(): TemplateResult<1> {
        return html`${keyed(this.properties?.elementId, html`<div>${this.headerTemplate()} ${this.bodyTemplate()}</div>`)}`;
    }

    protected headerTemplate(): TemplateResult<1> {
        return html`<header>
            <h3 class="title">Properties</h3>
            ${this.properties === undefined ? nothing : html`<h4 class="secondary-title">${this.properties?.label}</h4>`}
        </header>`;
    }

    protected bodyTemplate(): TemplateResult<1> {
        if (this.properties === undefined) {
            return html`<span class="no-data-message">The active diagram does not provide property information.</span>`;
        }

        const items = this.properties.items;
        const filteredItems = items.filter(item => {
            const label: string = (item as any)['label'];

            if (label !== undefined && this.searchText !== undefined) {
                return label.toLowerCase().includes(this.searchText.toLocaleLowerCase());
            }

            return true;
        });
        const { references: referenceItems, other: gridItems } = extractReferences(filteredItems);

        const gridTemplates = gridItems.map(item => {
            if (ElementTextProperty.is(item)) {
                return this.textFieldTemplate(item);
            } else if (ElementBoolProperty.is(item)) {
                return this.checkboxTemplate(item);
            } else if (ElementChoiceProperty.is(item)) {
                return this.dropdownTemplate(item);
            }

            return html`${nothing}`;
        });

        const referenceTemplates = referenceItems.map(item => {
            if (ElementReferenceProperty.is(item)) {
                return this.referenceTemplate(item);
            }

            return html`${nothing}`;
        });

        return html`<div class="body">
            <vscode-text-field
                class="search"
                placeholder="Search"
                .value="${this.searchText}"
                @input="${(event: any) => (this.searchText = event.target?.value)}"
            >
                <span slot="start" class="codicon codicon-search"></span>
            </vscode-text-field>
            <vscode-divider></vscode-divider>
            ${when(
                gridTemplates.length > 0,
                () => html`<div class="grid">${gridTemplates}</div>`,
                () => nothing
            )}
            ${when(
                gridTemplates.length > 0 && referenceTemplates.length > 0,
                () => html`<vscode-divider></vscode-divider>`,
                () => nothing
            )}
            ${referenceTemplates}
        </div>`;
    }

    protected textFieldTemplate(item: ElementTextProperty): TemplateResult<1> {
        const onChange = (event: CustomEvent): void => {
            const target = event.target as VSCodeTextField;
            this.onPropertyChange(item, target.value);
        };

        return html`<div class="grid-label">${item.label}</div>
            <div class="grid-value grid-flex">
                <vscode-text-field class="text-item" .value="${item.text}" @change="${onChange}"></vscode-text-field>
            </div>`;
    }

    protected checkboxTemplate(item: ElementBoolProperty): TemplateResult<1> {
        const onChange = (event: CustomEvent): void => {
            const target = event.target as VSCodeCheckbox;
            this.onPropertyChange(item, '' + target.checked);
        };

        return html`<div class="grid-label">${item.label}</div>
            <div class="grid-value">
                <vscode-checkbox class="bool-item" ?checked="${item.value}" @change="${onChange}"></vscode-checkbox>
            </div>`;
    }

    protected dropdownTemplate(item: ElementChoiceProperty): TemplateResult<1> {
        const onChange = (event: CustomEvent): void => {
            const target = event.target as VSCodeDropdown;
            this.onPropertyChange(item, target.value);
        };

        return html`<div class="grid-label">${item.label}</div>
            <div class="grid-value grid-flex">
                <vscode-dropdown .value="${item.choice}" @change="${onChange}">
                    ${item.choices.map(choice => html`<vscode-option .value="${choice.value}">${choice.label}</vscode-option>`)}
                </vscode-dropdown>
            </div>`;
    }

    protected referenceTemplate(item: ElementReferenceProperty): TemplateResult<1> {
        return html`<biguml-property-palette-reference
            .item="${item}"
            @property-navigate="${this.onPropertyNavigate}"
            @property-order-change="${this.onOrderChange}"
            @property-name-change="${this.onPropertyNameChange}"
            @property-create="${this.onPropertyCreate}"
            @property-delete="${this.onPropertyDelete}"
        ></biguml-property-palette-reference>`;
    }

    protected onPropertyChange(item: ElementProperty, value: string): void {
        const { elementId, propertyId } = item;

        this.dispatchEvent(
            new CustomEvent<Action>('dispatch-action', {
                detail: UpdateElementPropertyAction.create({
                    elementId,
                    propertyId,
                    value
                })
            })
        );
    }

    protected onOrderChange(event: CustomEvent<PropertyOrderDetail>): void {
        const { element, updates } = event.detail;

        this.dispatchEvent(
            new CustomEvent<Action>('dispatch-action', {
                detail: UpdateElementPropertyAction.create({
                    elementId: element.elementId,
                    propertyId: `${element.propertyId}_INDEX`,
                    value: JSON.stringify(updates)
                })
            })
        );
    }

    protected onPropertyNavigate(event: CustomEvent<ElementReferenceProperty.Reference>): void {
        const { elementId } = event.detail;
        this.dispatchEvent(
            new CustomEvent<Action>('dispatch-action', {
                detail: RefreshPropertyPaletteAction.create({
                    elementId
                })
            })
        );
    }

    protected onPropertyNameChange(event: CustomEvent<PropertyNameChangeDetail>): void {
        const { elementId, name } = event.detail;

        this.dispatchEvent(
            new CustomEvent<Action>('dispatch-action', {
                detail: UpdateElementPropertyAction.create({
                    elementId,
                    propertyId: 'NAME',
                    value: name
                })
            })
        );
    }

    protected onPropertyCreate(event: CustomEvent<ElementReferenceProperty.CreateReference>): void {
        this.dispatchEvent(
            new CustomEvent<Action>('dispatch-action', {
                detail: event.detail.action
            })
        );
    }

    protected onPropertyDelete(event: CustomEvent<PropertyDeleteEventDetail>): void {
        this.dispatchEvent(
            new CustomEvent<Action>('dispatch-action', {
                detail: DeleteElementOperation.create(event.detail.elementIds)
            })
        );
    }
}

function extractReferences(items: ElementProperty[]): { references: ElementReferenceProperty[]; other: ElementProperty[] } {
    const group = groupBy(items, item => item.type === 'REFERENCE');

    return {
        references: (group['true'] as ElementReferenceProperty[]) ?? [],
        other: group['false'] ?? []
    };
}

declare global {
    interface HTMLElementTagNameMap {
        'biguml-property-palette': PropertyPalette;
    }
}
