// client/packages/uml-components/src/menu/context-menu.component.ts
/*********************************************************************************
 * Copyright (c) 2023 borkdominik and others.
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at https://opensource.org/licenses/MIT.
 *
 * SPDX-License-Identifier: MIT
 *********************************************************************************/

import { autoUpdate, computePosition, flip, shift } from '@floating-ui/dom';
import { html, nothing, TemplateResult } from 'lit';
import { property, query } from 'lit/decorators.js';
import { when } from 'lit/directives/when.js';
import { BigElement } from '../base/component';
import { ContextMenuItemStyle, ContextMenuStyle } from './context-menu.style';

export function defineContextMenu(): void {
    customElements.define('big-context-menu', ContextMenu);
    customElements.define('big-context-menu-item', ContextMenuItem);
}

export class ContextMenu extends BigElement {
    static override styles = [ContextMenuStyle.style];

    get isVisible(): boolean {
        return this.contextMenu.hasAttribute('popup-show');
    }

    @property({ type: Object })
    reference: HTMLElement;

    @query('#context-menu')
    protected readonly contextMenu: HTMLDivElement;

    protected disposables: (() => void)[] = [];

    show(): void {
        this.contextMenu.setAttribute('popup-show', '');
        this.updateContextMenu();
        this.disposables.push(autoUpdate(this.reference, this.contextMenu, () => this.updateContextMenu()));
    }

    hide(): void {
        this.contextMenu.removeAttribute('popup-show');
        this.disposables.forEach(cb => cb());
    }

    override connectedCallback(): void {
        super.connectedCallback();
        document.addEventListener('click', this.handleDocumentClick.bind(this));
    }

    override disconnectedCallback(): void {
        super.disconnectedCallback();
        document.removeEventListener('click', this.handleDocumentClick);
    }

    protected override render(): TemplateResult<1> {
        return html`<div id="context-menu" @focus="${this.show}" @blur="${this.hide}">
            <div class="action-bar">
                <div class="actions-container">
                    <slot></slot>
                </div>
            </div>
        </div>`;
    }

    protected override updated(changedProperties: Map<string, any>): void {
        if (changedProperties.has('reference') && this.reference !== undefined) {
            this.updateContextMenu();
        }
    }

    protected handleDocumentClick(event: MouseEvent): void {
        const target = event.composedPath()[0];
        if (target === undefined) {
            return;
        }

        if (target instanceof HTMLElement) {
            if (
                event
                    .composedPath()
                    .filter(p => p instanceof HTMLElement)
                    .slice(1)
                    .some(p => [this.reference].includes(p as HTMLElement))
            ) {
                event.preventDefault();
            } else {
                this.hide();
            }
        }
    }

    protected updateContextMenu(): void {
        computePosition(this.reference, this.contextMenu, {
            placement: 'bottom-start',
            middleware: [flip(), shift()]
        }).then(({ x, y }) => {
            Object.assign(this.contextMenu.style, {
                left: `${x}px`,
                top: `${y}px`
            });
        });
    }
}

export class ContextMenuItem extends BigElement {
    static override styles = [...super.styles, ContextMenuItemStyle.style];

    @property()
    icon?: string;

    protected override render(): TemplateResult<1> {
        return html`<div class="action-item">
            ${when(
                this.icon !== undefined,
                () => html`<span class="codicon ${this.icon} action-icon"></span>`,
                () => nothing
            )}
            <span class="action-label"><slot></slot></span>
        </div>`;
    }
}

// client/packages/big-components/src/browser/components/menu/context-menu.component.tsx
/**********************************************************************************
 * Copyright (c) 2025 borkdominik and others.
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at https://opensource.org/licenses/MIT.
 *
 * SPDX-License-Identifier: MIT
 **********************************************************************************/

import { autoUpdate, computePosition, flip, shift } from '@floating-ui/dom';
import { useCallback, useEffect, useRef, useState, type ReactNode, type RefObject } from 'react';
import '../../../../styles/context-menu.css';

export interface ContextMenuProps {
    anchorRef: RefObject<HTMLElement>;
    children: ReactNode;
    isOpen?: boolean;

    onOpen?: () => void;
    onHide?: () => void;
}

/**
 * Context menu component
 * Allows to create a context menu that can be anchored to an element
 * with auto positioning
 */
export function ContextMenu(props: ContextMenuProps): React.ReactElement {
    const [isVisible, setIsVisible] = useState(false);
    /**
     * Reference to the context menu element itself
     */
    const contextMenuRef = useRef<HTMLDivElement | null>(null);
    const disposables = useRef<(() => void)[]>([]);

    const updateContextMenu = useCallback(() => {
        if (!props.anchorRef.current || !contextMenuRef.current) return;

        computePosition(props.anchorRef.current, contextMenuRef.current, {
            placement: 'bottom-start',
            middleware: [flip(), shift()]
        }).then(({ x, y }) => {
            if (contextMenuRef.current) {
                Object.assign(contextMenuRef.current.style, {
                    left: `${x}px`,
                    top: `${y}px`
                });
            }
        });
    }, [props.anchorRef]);

    useEffect(() => {
        if (props.isOpen && !isVisible) {
            setIsVisible(true);
            props.onOpen?.();
        } else if (!props.isOpen && isVisible) {
            setIsVisible(false);
            props.onHide?.();
        }
    }, [props, isVisible]);

    useEffect(() => {
        if (isVisible) {
            if (!props.anchorRef.current || !contextMenuRef.current) {
                return;
            }
            updateContextMenu();
            disposables.current.push(autoUpdate(props.anchorRef.current, contextMenuRef.current, updateContextMenu));
        } else if (!isVisible) {
            disposables.current.forEach(cb => cb());
            disposables.current = [];
        }
    }, [props.anchorRef, isVisible, updateContextMenu, contextMenuRef]);

    const handleDocumentClick = useCallback(
        (event: MouseEvent) => {
            const target = event.composedPath()[0] as HTMLElement;
            if (!target) return;

            if (
                event
                    .composedPath()
                    .filter(p => p instanceof HTMLElement)
                    .slice(1)
                    .some(p => p === props.anchorRef.current)
            ) {
                event.preventDefault();
            } else {
                props.onHide?.();
            }
        },
        [props]
    );

    const handleWindowBlur = useCallback(() => {
        props.onHide?.();
    }, [props]);

    useEffect(() => {
        if (props.anchorRef) {
            updateContextMenu();
        }
    }, [props.anchorRef, updateContextMenu]);

    useEffect(() => {
        document.addEventListener('click', handleDocumentClick);
        window.addEventListener('blur', handleWindowBlur);

        return () => {
            document.removeEventListener('click', handleDocumentClick);
            window.removeEventListener('blur', handleWindowBlur);
        };
    }, [handleDocumentClick, handleWindowBlur]);

    return isVisible ? (
        // eslint-disable-next-line react/no-unknown-property
        <div className='big-context-menu' popup-show='' ref={contextMenuRef} onBlur={() => setIsVisible(false)}>
            <div className='big-context-menu-bar'>
                <div className='big-context-menu-actions'>{props.children}</div>
            </div>
        </div>
    ) : (
        <></>
    );
}

export interface ContextMenuItemProps {
    icon?: string;
    children: React.ReactNode;
    onClick?: React.MouseEventHandler<HTMLDivElement>;
}

export function ContextMenuItem({ icon, children, onClick }: ContextMenuItemProps): React.ReactElement {
    return (
        <div className='big-context-menu-action' onClick={onClick}>
            {icon && <span className={`codicon ${icon} big-context-menu-action-icon`}></span>}
            <span className='big-context-menu-action-label'>{children}</span>
        </div>
    );
}
