// client/packages/big-components/src/browser/components/menu/menu.component.tsx
/**********************************************************************************
 * Copyright (c) 2025 borkdominik and others.
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at https://opensource.org/licenses/MIT.
 *
 * SPDX-License-Identifier: MIT
 **********************************************************************************/

import { VSCodeButton } from '@vscode/webview-ui-toolkit/react';
import { Children, isValidElement, useCallback, useRef, useState, type ReactNode } from 'react';
import { BigTooltip } from '../tooltip/tooltip.component.js';
import { ContextMenu, ContextMenuItem } from './context-menu.component.js';

export interface BigMenuProps {
    children: ReactNode;
}

export function BigMenu({ children }: BigMenuProps) {
    const menuButtonRef = useRef<HTMLDivElement | null>(null);
    const [isOpen, setIsOpen] = useState(false);

    const slotMenuTrigger = Children.toArray(children).find(child => {
        return isValidElement(child) && child.props['slot'] === 'menu-trigger';
    });

    const show = useCallback(() => {
        setIsOpen(true);
    }, []);

    const hide = useCallback(() => {
        setIsOpen(false);
    }, []);

    const toggle = useCallback(() => {
        if (isOpen) {
            hide();
        } else {
            show();
        }
    }, [hide, isOpen, show]);

    const renderSlotMenuTrigger = useCallback(() => {
        if (slotMenuTrigger) {
            return slotMenuTrigger;
        }

        return (
            <slot name='menu-trigger'>
                <VSCodeButton appearance='icon'>
                    <div className='codicon codicon-ellipsis'></div>
                </VSCodeButton>
            </slot>
        );
    }, [slotMenuTrigger]);

    return (
        <>
            <BigTooltip disabled={isOpen}>
                <div slot='anchor' id='menu-button' ref={menuButtonRef} onClick={toggle}>
                    {renderSlotMenuTrigger()}
                </div>
                <span slot='text'>More actions...</span>
            </BigTooltip>
            <ContextMenu anchorRef={menuButtonRef} isOpen={isOpen} onOpen={() => setIsOpen(true)} onHide={() => setIsOpen(false)}>
                <div id='menu-items'>{children}</div>
            </ContextMenu>
        </>
    );
}

export interface BigMenuItemProps {
    icon?: string;
    children: ReactNode;
    onClick?: React.MouseEventHandler<HTMLDivElement>;
}
export function BigMenuItem({ icon, children, onClick }: BigMenuItemProps) {
    return (
        <ContextMenuItem icon={icon} onClick={onClick}>
            {children}
        </ContextMenuItem>
    );
}

// client/packages/uml-components/src/menu/menu.component.ts
/*********************************************************************************
 * Copyright (c) 2023 borkdominik and others.
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at https://opensource.org/licenses/MIT.
 *
 * SPDX-License-Identifier: MIT
 *********************************************************************************/
import { Button as VSCodeButton } from '@vscode/webview-ui-toolkit';
import { html, PropertyValues, TemplateResult } from 'lit';
import { query } from 'lit/decorators.js';
import { BigElement } from '../base/component';
import '../global';
import { Tooltip } from '../tooltip/tooltip.component';
import { ContextMenu, ContextMenuItem } from './context-menu.component';
import { MenuStyle } from './menu.style';

export function defineMenu(): void {
    customElements.define('big-menu', Menu);
    customElements.define('big-menu-item', MenuItem);
}

export class Menu extends BigElement {
    static override styles = [...super.styles, MenuStyle.style];

    @query('#menu-button')
    protected readonly menuButton: VSCodeButton;

    @query('#context-menu')
    protected readonly contextMenu: ContextMenu;

    @query('#tooltip')
    protected readonly tooltip: Tooltip;

    show(): void {
        this.contextMenu.show();
    }

    hide(): void {
        this.contextMenu.hide();
    }

    toggle(): void {
        if (this.contextMenu.isVisible) {
            this.hide();
        } else {
            this.show();
        }
    }

    protected override render(): TemplateResult<1> {
        return html`<big-tooltip .disabled=${this.contextMenu?.isVisible}>
                <vscode-button slot="anchor" id="menu-button" appearance="icon" @click="${this.toggle}">
                    <div class="codicon codicon-ellipsis"></div>
                </vscode-button>
                <span slot="text">More actions...</span>
            </big-tooltip>
            <big-context-menu id="context-menu" @visibility-change=${() => this.requestUpdate()}>
                <div id="menu-items">
                    <slot></slot>
                </div>
            </big-context-menu>`;
    }

    protected override firstUpdated(_changedProperties: PropertyValues<this>): void {
        this.contextMenu.anchorReference = this.menuButton;
    }
}

export class MenuItem extends ContextMenuItem {}
