// client/da/grilling/examples-dj/biguml-example/packages/biguml-components/src/property-palette/web/property-palette-webview.component.ts
/*********************************************************************************
 * Copyright (c) 2023 borkdominik and others.
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at https://opensource.org/licenses/MIT.
 *
 * SPDX-License-Identifier: MIT
 *********************************************************************************/

import { ElementProperties, RefreshPropertyPaletteAction, SetPropertyPaletteAction } from '@borkdominik-biguml/biguml-protocol';
import { Action } from '@eclipse-glsp/protocol';
import { html, TemplateResult } from 'lit';
import { query, state } from 'lit/decorators.js';
import { BigElement } from '../../base/component';
import { useToolkit } from '../../toolkit';
import { VSCodeConnection } from '../../vscode/vscode-api';
import { PropertyPalette } from '../property-palette.component';

export function definePropertyPaletteWebview(): void {
    customElements.define('big-property-palette-webview', PropertyPaletteWebview);
}

export class PropertyPaletteWebview extends BigElement {
    @query('#component')
    protected readonly component: PropertyPalette;

    @state()
    protected elementProperties?: ElementProperties;

    protected connection = VSCodeConnection.instance();
    protected clientId?: string;

    override connectedCallback(): void {
        super.connectedCallback();
        useToolkit();

        document.addEventListener('contextmenu', event => {
            event.stopImmediatePropagation();
        });

        this.connection.listen(this.onConnectionAction.bind(this), Action.is);

        this.dispatchAction(RefreshPropertyPaletteAction.create());
    }

    protected override render(): TemplateResult<1> {
        return html`<big-property-palette
            id="component"
            .clientId="${this.clientId}"
            .properties="${this.elementProperties}"
            @dispatch-action="${this.onDispatchAction}"
        ></big-property-palette>`;
    }

    protected onConnectionAction(action: Action, clientId: string): void {
        if (SetPropertyPaletteAction.is(action)) {
            this.clientId = clientId;
            this.elementProperties = action.palette;
        } else {
            console.warn('Unsupported action', action);
        }
    }

    protected onDispatchAction(event: CustomEvent<Action>): void {
        this.dispatchAction(event.detail);
    }

    protected dispatchAction(payload: Action): void {
        this.connection.post<Action>({
            clientId: this.clientId,
            command: 'dispatch-action',
            payload
        });
    }
}

// client/packages/big-property-palette/src/env/browser/webview/property-palette.webview.tsx
/**********************************************************************************
 * Copyright (c) 2025 borkdominik and others.
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at https://opensource.org/licenses/MIT.
 *
 * SPDX-License-Identifier: MIT
 **********************************************************************************/
import 'reflect-metadata';

import { VSCodeConnector } from '@borkdominik-biguml/big-components';
import { createRoot } from 'react-dom/client';
import { PropertyPalette } from '../property-palette.component.js';

import '../../../../styles/index.css';

const element = document.getElementById('root');
if (!element) {
    throw new Error('Root element not found!');
}
const root = createRoot(element);
root.render(
    <VSCodeConnector>
        <PropertyPalette></PropertyPalette>
    </VSCodeConnector>
);
